### ISSUE TITLE
Optional "Display Name" for options

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#104]
On the project I have been working on, we have a bunch of products that all have options with the same name. However, for ease of use, it's easier to actually make those options be completely separate from one another.

(For instance, the size of a "shed" is completely different than the "size" of a bed, and therefore they should be separate options). 

To fix this, I created an option "Display Name" which is set by the admin. In the front end, if their is a display name, the controller shows that, otherwise it shows the option name instead.

Would anyone mind this functionality being added to copona?

<img width="691" alt="screen shot 2017-03-01 at 12 07 48 pm" src="https://cloud.githubusercontent.com/assets/4703516/23471699/33bdbf68-fe78-11e6-9a7a-a6bf97b53935.png">

**Comment by arnisjuraga** [comment]
Let's merge. Just check the layout - as these fields settings are logically connected, check how they look in admin with more than one language? In our projects, many of them have even 3 languages as default. 

Also - have you checked, that this Display name then must be used also in Cart and Order, when created.
