### ISSUE TITLE
checkout issue

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#109]
1) Checkout doesn't ever ask for shipping address.

2) A few strings have been hardcoded into it - those should be in the language file.

In english, I assume they are (from top to bottom):"Total", "Amount Due", "Customer Information".
 (image removed)

**Comment by arnisjuraga** [comment]
Yes, must be fixed asap

**Comment by arnisjuraga** [comment]
Looks Legit
![image](https://cloud.githubusercontent.com/assets/2185289/23514080/db8203f2-ff6e-11e6-8a50-fdc93d313388.png)
