### ISSUE TITLE
New installation script

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#115]
Can someone please test out the new install script?

1) It should create the tables with all current migrations implemented (the ones from the last few days hadn't been).

2) If the server is Apache and Mod_Rewrite is enabled, it automatically creates the .htaccess file and enables SEO URL's. This needs to be tested with Nginx to insure it doesn't get inadvertently enabled there too... I don't see why it would but would like someone to test.

TO DO:

Will eventually need to change the RewriteBase to reflect the director Copona is installed in, if its not installed in the root directory for a domain.

**Comment by lucasjkr** [comment]
@arnisjuraga created a digital ocean droplet for testing with Nginx. We tried installing, and it worked mostly correctly (doesn't turn on SEO URL's) - but it writes localhost as the values for HTTP_SERVER and HTTPS_SERVER - we'll need to troubleshoot the Nginx installation process further to make sure we are writing the correct value in those constants.

**Comment by lucasjkr** [comment]
Specifically, Nginx appears to return 'localhost' when calling $_SERVER['SERVER_NAME']

**Comment by arnisjuraga** [comment]
ok, `SERVER_NAME` is taken from web server config. If there is only one host on current server, then it will work with any hostname directed to that IP, but will return server config `SERVER_NAME`, which is `localhost` at the moment.

`HTTP_HOST`, on the other hand, is something, which is sent by browser. If you change the address you install from. 

Check both Nginx and Apache - they have it and with a reflected value.

**Comment by lucasjkr** [comment]
See #117

**Comment by arnisjuraga** [comment]
@lucasjkr have we done everything then for this issue?

**Comment by lucasjkr** [comment]
Yes, I'll close this. But from time to time, we'll just re-test on that new server you set up.

**Comment by arnisjuraga** [comment]
Right. I have added Composer to the server install.
