### ISSUE TITLE
`apache_get_modules()` in `/install/controller/install/step_3.php` throws a fatal error during installation, if PHP is installed as PHP-FPM

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#122]
`PHP Fatal error:  Call to undefined function apache_get_modules() in /install/controller/install/step_3.php`

**Comment by prhost** [comment]
maybe try `function_exists('apache_get_modules')` before using the function

**Comment by lucasjkr** [comment]
We're not using the function at all anymore, we're just checking output of phpinfo(), since any installation of PHP should have that.

See line 115 https://github.com/copona/copona/pull/123/commits/a9539e8adafe904473579b52f66b3d4d5449d7d5 

Do you think that's an OK approach?
