### ISSUE TITLE
Integration of Whoops

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#138]
The Whoops is aaaaamazing! 

Thanks again to @kallef110  in 6b179f7a10293f62edcdb85716f2b837c11f0fad for  bringing this to Copona!
Just as an example of ```missing comma```

![image](https://cloud.githubusercontent.com/assets/2185289/26496012/8abb98d6-422e-11e7-82ae-87d1bc29d4c9.png)

**Comment by prhost** [comment]
This tool is very good, in the future we will customize this screen, when copona has its own UIkit, and also control the view by enviromnent, so when it is in production, the developer can disable the screen.

**Comment by arnisjuraga** [comment]
@prhost can you, please, make some upgrade?

- can failed MySQL selects also be passed to Whoops?
- configurable option in config.php or Admin, to turn Whoops off for production sites?

**Comment by prhost** [comment]
Yes I can do this, I'm only a short time, I ended up closing some projects recently, so I did not collaborate at all these days. As long as I have time, I can deal with it

**Comment by landsman** [comment]
Oh I missed this issue, do you think that Whoops is better than Tracy?
Tracy can handle AJAX request, have easy modular panels :)
https://github.com/copona/copona/issues/141

**Comment by prhost** [comment]
no, i just think whoops may be just for the error screen, and tracy which is more complete as an auxiliary tool, in that case an extension to part.

**Comment by arnisjuraga** [comment]
@landsman can you integrate it, and see, how it reacts on/with Whopps somewhere?
I can setup a test server if you need.

**Comment by prhost** [comment]
@arnisjuraga
I wanted to say with "can failed MySQL selects also be passed to Whoops?
Any mysql error, inside the driver, is triggered an exception and the whoops shows the error.

**Comment by arnisjuraga** [comment]
Strange, you are right - MySQL exception errors are triggered by Whoops correctly. I can't find the case, where I thought the error is not showing up. Only configuration settings then can be useful:
* configurable option in config.php or Admin, to turn Whoops off for production sites

**Comment by prhost** [comment]
I'm reshaping the configuration part before I can do this job.

**Comment by CZechBoY** [comment]
Why Whooops was choosen instead of better/more mature library Tracy?

**Comment by prhost** [comment]
Can try to implement tracy if he prefers, whoops was chosen because before that he had nothing, and he is famous too, he just does not have debug bar, but feel free to help collaborate, send a pull request if you prefer (:

**Comment by arnisjuraga** [comment]
Tracy and Whoops are very different packages. 
The idea of Whoops, (as it appears, @landsman already asked this question, and you can check the gentlemen's answer filp/whoops/issues/506) is to deliver rich and neat \Exception errors page. Which is _aaaaamazing_!

I have not worked with Tracy, I am using Xdebug when it's necessary. But I prefer to choose tools, which does as much as I need, and (hopefully) not more. It's an experience from choosing the performance, configuration and usability. There is nothing bad or wrong about Tracy. It's just a different tool, as there is a load of them.

But yes - from the developer, I would love to try Tracy.

**Comment by arnisjuraga** [comment]
Closing this, as we are using Whoops a lot, if we need something more, we can do that as an extension or crate a new issue.
