### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by stefanhuber** [copona/copona#144]
Unfortunately I have some problems with the docker installation.

 - I think the variable names are not correct, or rather why inside the docker-compose.yml there are other references to environment variables, not present inside the .env file. e.g. MYSQL_DATABASE is inside the .env file and ${DB_DATABASE} is inside the docker-compose.yml file.
 - Would it be possible to use different ports for the database server and also the webserver. As on my machine i have a mysql database and webserver running which occupy these ports already.

I am a novice with docker, however I would like to use it for development and also for deployment. Am I doing something wrong, or are the above mentioned issues real issues?

**Comment by prhost** [comment]
I sent a commit by repairing `.env`, please copy back from `.env.example`.

About changing the port you can duplicate `docker-compose.yml` to `docker-compose-dev.yml` or docker-compose-stefanhuber.yml, modify what you need and then execute passing the paramenter -f `docker-compose -f docker-compose-othername.yml up -d`

`docker-compose -f docker-compose-othername.yml start`
`docker-compose -f docker-compose-othername.yml stop`
`docker-compose -f docker-compose-othername.yml restart`

**Comment by arnisjuraga** [comment]
Just small linkups with Opencart issues, if someone is looking up:
https://github.com/opencart/opencart/pull/5365
opencart/opencart/issues/4897#issuecomment-269477734 
https://github.com/opencart/opencart/pull/3784
