### ISSUE TITLE
PHPMailer integration

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#15]
Can we?

**Comment by btafoya** [comment]
I will gladly submit a pull request with my PHP mailer integration.

**Comment by arnisjuraga** [comment]
We don't use composer yet. So we will have to include it together with PHPMailer library itself. I believe, PHP Mailer licence allows it?

**Comment by btafoya** [comment]
OpenCart already has Composer support and is required for some of the payment providers. Look at the pull request I submitted and you will see the changes made to include it.

**Comment by prhost** [comment]
I do not think opencart comes standard as a lot of payment method and freight, it should be all extension, many of the forms of payment are "impregnated" in the code, there are traces in places that should not have as assets added in the controller Checkout and complete libraries together. But I think that's a subject for another issue.

**Comment by arnisjuraga** [comment]
I have merged it @3d228e1
