### ISSUE TITLE
Hide alert about '/install/' folder in Admin, if in DEV mode

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#157]
Can we?

If DEV mode is on, we should hide "install" folder alert. @prhost can you do that?

**Comment by prhost** [comment]
How about removing the install folder automatically after the installation is complete?

**Comment by arnisjuraga** [comment]
Why? It's a bad practice.

**Comment by prhost** [comment]
I think it's a bad practice to maintain, I do not think it's safe to keep an installation folder in the project after the project has already been installed, and getting installed several times in development means something is wrong. `Install/` just install database and `.env`, does not restore copona files.

Yes you have to keep in git the developers who collaborate for the copona only, whoever picks up the copona to develop your store must do the manual update, via package or panel and not via fork of copona.

If it is a bad practice, why have the messages at the end of the installation and the panel saying to remove the install folder?

**Comment by arnisjuraga** [comment]
Sorry about that "bad practice". The warning have been left there just from OC times. I can't say why oc haven't been able to protect it :) instead decided to use such a warning message instead. 

I believe, install folder can be protected with php.

Just deleting the system files (install folder) is a bad practice. It breaks consistency of an application, I think :(

**Comment by prhost** [comment]
So keeping the install folder a good practice? The only advantage I see is to avoid conflict when it comes to pulling upgrades from the upstream copona to your fork, but you should only worry about who is developer of copona, other developers who are just developing their store.

Trying to protect the install folder is not a good practice.
Depending on the core of copona to work and any change in the project it breaks, is not a good practice.
Keeping unnecessary files in the project is not a good practice.
Checks in the copone to identify if it has not yet been installed and redirect to the install folder even after it does not exist, this verification will always be verified, not a good practice.

So my idea to separate the install folder into another repository, just for UI installation, to support shared servers that do not provide ssh.

Sorry for that, it's just an outburst. I hate the install folder 😔

**Comment by MartanLV** [comment]
Hello there. My thoughts - install folder could be named "copona-vendor" and preserve it's place after the process of "bootstrap" for convenience ... I come from Laravel world - there we check for a presence of specific file to determine if app is in maintenance mode or not. I think the artisan command just renames the file from "on" to "off" ... anyways - I see copona might use similar, and cheap technique - to check for specific file in `copona-vendor/` (i hate the dirctory name "install" too) at every boot to determine if bootstrap is necessary.

p.s. laravel command tool maintains that mintainence file too, but it can be done by hand. ;)

**Comment by prhost** [comment]
@MartanLV your idea is interesting, currently two things are checked whether there is to give understanding that the project is installed or not.

1. file `.env` exist
2. folder install exist (because it will be redirected to it)

The only thing that makes copona keep install is for more lazy developers and servers without ssh. I do not think it's bad to have an installer, I think it's bad to be together in the project.

**Comment by MartanLV** [comment]
yes, I agree that it is inconvenient to carry an install directory within a project. Install and reinstall would rather be managed by a standalone commandline tool.

**Comment by prhost** [comment]
Only to understand that this is in the way if the `debug` is enabled, since the `app_env` can be defined what you want, the developer can abbreviate to `dev` or` develop` or `development`...

**Comment by RaidoDev** [comment]
Great!
