### ISSUE TITLE
Admin left menu not responding when minimized

### ISSUE THREAD

**Issue by btafoya** [copona/copona#17]
The left admin menu icons do nothing unless the menu is expanded.

**Comment by arnisjuraga** [comment]
Ok, well check. There are changes for admin menu to get rid of flickering. Well check minimized menu.

> Please, be aware - this project is in DEV mode, so - there are a lot of changes ongoing and done daily. Update with git often, just use it Live with on your own responsibility. 

**We will be happy, if you will post as many issues and feature requests as you can! :)**

**Comment by arnisjuraga** [comment]
Google Chrome works fine, but Firefox is affected.

**Comment by arnisjuraga** [comment]
@btafoya please pull the changes, and close the issue, if it's resolved.

**Comment by arnisjuraga** [comment]
Closing as fixed. Reopen it if you still have a problem
