### ISSUE TITLE
Change order statusses in admin - statuses shows in incorrect language

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#181]
Admin language set to: lv

Go to Missed Orders and View order. See statuses.

![image](https://user-images.githubusercontent.com/2185289/30211627-72a4bb46-94aa-11e7-875c-6124e7c4401d.png)

**Comment by prhost** [comment]
did you register your status in your language? Admin > Localisation > Order Statues

**Comment by arnisjuraga** [comment]
:D you are right, 
I was misleaded, because "Missing orders" is not taken from order statuses, and that one was translated correctly, I decided, that problem is in system. 
No bug at all then. Thanks.
