### ISSUE TITLE
Simplify config.php entries

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#19]
for majority of users, the setting for database and application forlders locations are always and always the same. 
Sometime you want to change /admin/ folder name to something different. So then yo can do it in admin's config.php file.

But all the other settings, except Database connection is quite useless in config.php.

Let's remake it. :)

**Comment by prhost** [comment]
All this configuration except database, is really useless, everything can be dynamic and part of the new core, and the redundancy of having almost the same config.php is bullshit. I really like laravel, a lot of my project is based on it, you'll hear me comment a lot about laravel hehe. In laravel the configuration works similar to the image. A place with multiple settings files and them being loaded dynamically. Also it has the configuration by environment variables, which I find very useful for CI / CD implementation

https://laravel.com/docs/5.3/configuration

![](https://cloud.githubusercontent.com/assets/3984760/12620790/d3435560-c504-11e5-9ef0-6587505e1703.jpg)
