### ISSUE TITLE
Default filemanager.php search does not work for partical string

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#2]
latest Opencart version Filemenager image search does not work with partial string search in filenames or folder names for images.

Consider implementing this https://github.com/opencarteli/opencart/commit/6d85c56c257349fc2e3360fdc3c33136470c56f7

**Comment by arnisjuraga** [comment]
+ wouldn't it be better to implement case-insensitive search?
This requires additional helper function, because `glob()` does not support case-insensitive search.

**Comment by prhost** [comment]
Since we are going to revolutionize, I vote to change filemanager to an already stable one like https://github.com/Studio-42/elFinder or responsivefilemanager.com

I've implemented the responsivefilemanager in my opencart, and it's pretty easy, I just had a problem loading many photos, it does not do paging, and it does not load through ajax. In that case I vote for the elfinder.

**Comment by arnisjuraga** [comment]
We should create a vote! We need both - WYSIWYG editor and FileManager.

I have implemented the "old" good one  CKEditor - and http://responsivefilemanager.com has support for that. Seem easier to implement then. 
On the other hand - the thing users need really often - is "image cropping, resizing" in image browser, so - some kind of simple image editor. 

I have seen some implementations on ElFinder. But you  can look even on this: https://github.com/Studio-42/elFinder/pull/242#issue-3693039

**Comment by prhost** [comment]
The responsivefilemanager has integration with the aviary that is now adobe, already does all this work of image manipulation and much more.

The elfinder already has integration with ckeditor for being the same developer, and it also already has native at least crop, resize and rotation.

https://creativesdk.adobe.com/features/#/creative-tools.html

![](http://www.responsivefilemanager.com/images/screenshot4.jpg)

**Comment by arnisjuraga** [comment]
@prhost so, your choice would be?

**Comment by prhost** [comment]
I do not know hehe, resposivefilemanager is very good, but it has a big problem that it is the support for many images in the same folder, it does not load the images bit by bit, loads everything in time, and it can crash the browser. But installing and using it is very easy, I needed to make some adjustments to the javascript but it was not much. The elfinder loads the files into pieces so it will not have much of a problem with that.

**Comment by prhost** [comment]
I think I vote for the same elfinder, much more stable, I already integrated it once, I think it should not be laborious, I think of making a way to configure any type of filesystem as external cdn that the elfinder support, via a new form of configurations

Some cool elfinder themes:
Https://github.com/RobiNN1/elFinder-Material-Theme
Https://github.com/StudioJunkyard/elfinder-bootstrap-theme
Https://github.com/lokothodida/elfinder-theme-windows-10

**Comment by arnisjuraga** [comment]
To be honest - I like the look and feel of responsivefilemanager.com At the same time - image loading "one by one" - it's  just no acceptable. Then my choice have to be - elFinder.

elFinder looks too .. nerdy to me. But, let's wait for other alternatives? Suggestions?

**Comment by prhost** [comment]
Elfinder is complete, I believe we will not soon have any problem with file manager, until CDN it supports. Unfortunately its documentation and syntax is not very friendly, but I already integrated it once, I think it would not be impossible.

I have already researched file managers for a long time, and in php there is not much, usually the platforms make their own manager, the 2 that are stacked are those.

I vote on elfinder.

**Comment by arnisjuraga** [comment]
Ok, can you try to integrate it and give us for tests?

**Comment by prhost** [comment]
I can try to implement and pass it to you yes yes, I just do not know how long I will take and when to start.

**Comment by arnisjuraga** [comment]
Ok, @prhost  just let us know. I have few other tasks prioritized now, but I am willing to return to this in the near feature too and can give you some help, but not now.

**Comment by arnisjuraga** [comment]
Bump! 👍 
I have faced the problem with the new filemanager again ...
Could we just return to the old one?

The main problem with the old one - performance problems on a folders with many images.

**Comment by arnisjuraga** [comment]
This one is becoming more and more actual.

**Comment by arnisjuraga** [comment]
Ideas?

**Comment by prhost** [comment]
change native file manager to elfinder

**Comment by prhost** [comment]
https://www.filestack.com/

**Comment by RaidoDev** [comment]
@prhost this is a commercial solution. This can't replace file manager in Copona, although - we can plan an integration if there would be a request for that?

**Comment by prhost** [comment]
sorry, i have not seen it right, I just found it, it has no open source version :/ I think it's best to continue with elfinder.

**Comment by arnisjuraga** [comment]
Elfinder removed from core and created added as Plugin 
https://github.com/copona/ElFinderFileManager

This still does not replace Elfinder as image selector in content management, but this at least allows to upload, edit and alter images and files from admin.

Must have tests for security also, but thats ok for now.
