### ISSUE TITLE
Fatal error on admin login, ZipArchive not installed (because of currency update)

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#204]
```
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /public_html/admin/model/localisation/currency.php:144
```

**Comment by prhost** [comment]
PHP needs to have the zip extension installed

**Comment by arnisjuraga** [comment]
Yes (just for notes: https://stackoverflow.com/questions/3872555/fatal-error-class-ziparchive-not-found-in )
It seems, ZIP extesion *is* checked during install, so this error can appear only in migration scenarios. All good.
