### ISSUE TITLE
PHPmailer default encoding problem

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#40]
There is a problem with encoding.

If ad add non-latin characters, then mail contains "garbage":

"šņākoņa" will appear as: 

![image](https://cloud.githubusercontent.com/assets/2185289/21595795/7a0997dc-d13a-11e6-93bd-91eba9175587.png)

**Comment by arnisjuraga** [comment]
@btafoya can you take a look? 
@prhost

**Comment by btafoya** [comment]
Sure thing.

**Comment by prhost** [comment]
@btafoya puts `$mail->CharSet = 'UTF-8';` and already see about my comment in the last merge request please.

**Comment by btafoya** [comment]
@prhost I am not sure what you are asking? Yes, I am aware of the CharSet method and am already testing it. What was the comment from the last merge request?

**Comment by prhost** [comment]
@btafoya 
See if you can see the review I sent, here for me appears in which line I commented and that is pending.
https://github.com/copona/copona/pull/37

**Comment by btafoya** [comment]
If you are referring to composer support, it is also included in the pull request. Otherwise please elaborate.

**Comment by prhost** [comment]
@btafoya 
I'm not referring to the composer, it's just a bug shot that can be handled in the tray catch that you put in, I commented well in the line of code when the merge request existed, and it appeared as a review pending for you. Open your last merge request you submitted, and see if it looks the same to you.

![screen shot 2017-01-02 at 20 35 41](https://cloud.githubusercontent.com/assets/3984760/21597046/18f23cd8-d12b-11e6-985c-92374e30536f.png)

**Comment by btafoya** [comment]
@prhost It is already covered by a try statement for phpmailer errors. The
$mail->send() does no longer throw an exception as requested during the
original merge request.



*Brian Tafoya*
321.266.0951
btafoya@briantafoya.com
http://briantafoya.com

"No trees were harmed sending this e-mail, but several billion electrons
were horribly inconvenienced!"


INTERNET MAIL CONFIDENTIALITY NOTICE

This E-mail is covered by the Electronic Communications Privacy Act,
18 U.S.C. §§ 2510-2521 and is legally privileged. This information is
confidential information and is intended only for the use of the individual
or entity named above. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited.

http://www.law.cornell.edu/uscode/text/18/2511

**Comment by btafoya** [comment]
@prhost FYI, I do not have access to the review comments.

**Comment by prhost** [comment]
I thought you might see, sorry.

On the exception, then it would be nice to just leave `$mail->send()` without if and check if it got error since it is handled and fired from within.

**Comment by btafoya** [comment]
The if() check is still required for instances when phpMailer returns an error that is not an exception. (Which it does for many events.)

**Comment by prhost** [comment]
Then switch to:
```
if(!$mail->send()) {
      throw new \Exception('Mail Configuration Error: ' . $mail->ErrorInfo);
}
```

So all errors are handled in one place.

**Comment by btafoya** [comment]
I was asked not to throw a fatal error... That was the entire issue originally.

**Comment by btafoya** [comment]
See the original commit and you will see I had the exception being thrown. Thus project needs some consistency amongst its team members in order to prevent duplicate efforts.

**Comment by arnisjuraga** [comment]
I have merged it. @prhost, please, create a new issue if you have any concern.
