### ISSUE TITLE
Simple "dirty" update script for Database changes

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#54]
At the point, we have time-to-time small sql changes.
But with multiple instances, it's hard to rerun install.sql (obviously) 
but putting them into admin/catalog some "autostart" PHP script (upon login etc) anyway is wrong.

So, we have created simple `/update.php` script.

One must be executed after very code update. Will do no harm, but all sql changes must be added.
At the moment it has just some silly updates I needed for sync between instances. 

Suggest better solution or update it.

PDO, e.g.

**Comment by prhost** [comment]
I like to use migration phinx, it's very good and easy to use, I can install it in the copon if you want.

**Comment by arnisjuraga** [comment]
Yes, please. With some doc and instructions I am ready to test.

2017. gada 1. febr. 21:28, "Kallef Alexandre de Souza" <
notifications@github.com> rakstīja:

**Comment by prhost** [comment]
Did not you want me to add the migration? I sent a pull request. Now it has conflict, update.php has been changed

**Comment by arnisjuraga** [comment]
@prhost sorry about that, I just missed your pull request. 
I'll check, what's the conflict and let's merge.

**Comment by arnisjuraga** [comment]
Great! First migration done! Phinx is a way to go for a development. 

The catch still is - you need to use composer for this. So - developing on shared hostings without composer support is not yet possible. So, is there any workaround for that?

**Comment by prhost** [comment]
There are several ways, but if you have SSH access to shared hosting then it will work, just have the correct php version.

But it can also be done a webhook (page accessed via browser that triggers something) and inside it you execute something like `exec ('php vendor / bin / phinx ...')`

What we use most in our development is CI / CD with gitlab, so we do all the phpunit treatment, dependency as composer and migration by la, only then we go up to the hosting.

**Comment by prhost** [comment]
http://docs.phinx.org/en/latest/commands.html#running-phinx-in-a-web-app

voilá (:

**Comment by arnisjuraga** [comment]
So, let's use phinx for now from command line.
In the future - we'll see, do we need to create any `update` script for database update run from web.
