### ISSUE TITLE
Code formatting - spaces or tabs?

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#58]
Hi everyone!

@JJKalnins  and @prhost raised small discussion about code format (https://github.com/copona/copona/pull/57#issuecomment-276937311) 

At the momen all Copona code is formatted with:
- indentation = TAB
- IDE TAB size = 2

Also - if there is some file left with "old" formatting (using spaces), then any commit will have messed up with a bunch of "whitespace changes". 

Unfortunately - Github uses tab-size 8 for viewing files.  And this is the main headake.

Workaround is to use get parameters in Github `ts=2&w=1` like:
`https://github.com/copona/copona/pull/57/commits/1a5a1ca0dedd14a9dbf1a08eb5d43ee8770fdfc2?w=1&ts=1` 

So, the question:

- Should we reformat all project to "2 spaces" indentation?

**Comment by prhost** [comment]
Now @JJKalnins fixed the hehe indentation correctly. It's just folks actually follow the psr-2 standard that's on the wiki.

...
Code MUST use an indent of 4 spaces, and MUST NOT use tabs for indenting.

N.b.: Using only spaces, and not mixing spaces with tabs, helps to avoid problems with diffs, patches, history, and annotations. The use of spaces also makes it easy to insert fine-grained sub-indentation for inter-line alignment.
...

http://www.php-fig.org/psr/psr-2/#indenting

**Comment by ADDCreative** [comment]
The original Opencart coding standard is to only use tabs for indenting, expect in .tpl files. It should not matter what your tab size is set to as long as tabs are only used in the correct places.
https://github.com/opencart/opencart/wiki/Coding-standards#indentation

> Indentation
> 
> PHP files must be indented using the TAB character. 4 space tabs are not supported.
> 
> HTML in template files (.tpl) must be indented using 2 spaces, not 4 spaces or TABS. JavaScript must be indented using the TAB character.

**Comment by prhost** [comment]
We need to adopt one of the two patterns. I thought we already decided to use psr-2. @arnisjuraga?

Even IDE like PHPSTORM uses prs-2. I believe it's easier to find plugins or formatting to install in the psr-2 IDE than an Opencart standard.

**Comment by arnisjuraga** [comment]
As we have most of source code still from Opencart, our IDEs have formatting styles configured as much as similar we can to Opencart code. As you know ... because of VQmod and OCmod - reformatting file usually breaks modifications. This is so annoying, but still counts.

Well change to 4xSpaces indentation now. I will reformat Copona code in a near future.

**Comment by arnisjuraga** [comment]
We need to agree on some PSR-2 modifications. E.g. - we want to align array key => pairs, 

https://github.com/copona/copona/wiki/Dev-Codex
