### ISSUE TITLE
Question on database structure

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#77]
What are your thoughts on converting from MyISAM tables to InnoDB?

Most tables are set as MyISAM, and I understand that the OC team prefers it that because it’s faster to read from. But if we use go with InnoDB throughout, it could unlock some cool things in the future (cascades, etc)

http://stackoverflow.com/questions/5342852/how-to-use-delete-cascade-on-mysql-myisam-storage-engine

InnoDB also supports row level locking, rather than table level, which could stop some contention issues

https://support.rackspace.com/how-to/mysql-engines-myisam-vs-innodb/

And transaction support COULD be useful, I actually had a crappy VQMOD that, when attempting to delete some data, had typo in one query which meant some data was removed, but other stuff stayed. If done inside of a transaction, we could have rolled back to the previous state. 

https://support.rackspace.com/how-to/mysql-engines-myisam-vs-innodb/

 Just food for thought for the future, I think it would open the way to more enhancements down the road.

**Comment by arnisjuraga** [comment]
Thre have been a lot of discussions on DB engine in Opencart forum and Github.
To be true, I don't have any reasonable opinion. Just checked some examples: 
- Wordpress == InnoDB
- Wordpress Woocommerce == InnoDB
- Magento == InnoDB
- PrestaShop (old version I have on my test server) == MyISAM. 

The one thing, which I drove my attention:

`MyISAM is stagnant; all future enhancements will be in InnoDB`

Althought, MyISAM supports Full Text indexing (and I have improved search plugin which uses Full Text Indexing), InnoDB supports it too (starting MySQL 5.6).

The problem/question is - how easily is to convert everything? At least - for fresh installs?

I don't see huge benefits from this, but for future sake - **Let's move to InnoDB**! It must be done ASAP! 💃 

@prhost - can it be done in phixn migrations too?

**Comment by lucasjkr** [comment]
Fresh installs it's easy, we just set the engine for each table in install/opencart.sql - I'll update and test that now.

Interested in @prhost's response about phinx - I haven't used it, but would love to understand it and be able to use version control for database like that provided by artisan (for this, and other projects)

**Comment by arnisjuraga** [comment]
Hmmmm.... : https://github.com/robmorgan/phinx/issues/1008

**Comment by lucasjkr** [comment]
I took a brief look at Phinx docs. It doesn't look like engine is a attribute that Phinx can set. I may be wrong.

Also, I wonder about directly integrating Phinx into the project, rather than having it be a composer dependency. I'm not a lawyer, but it seems like the MIT license would allow it.

Reason being, that would perfectly address my other suggestion (the one that was closed on OC) - to have a mechanism for extension developers to be able to modify the database for their plugins in a simple, uniform manner, which Phinx provides.

There's probably a lot of work still to get support for Postgres/MS SQL on even footing, so Phinx isn't the complete solution, just lays the groundwork.

**Comment by prhost** [comment]
We can convert all opencart.sql to migration, it by default is already innoDb and we have also been able to create forean key, do delete cascate, to leave bank accountability, which is safer and faster than doing method in the model that deletes all records Related to some ID. Or do a migration just to convert all the engine. I prefer to convert the entire sql installation, easier to maintain then.

**Comment by prhost** [comment]
@lucasjkr 
Besides phinx, it has also eloquent, I implemented it with ORM, but it also supports migration, seed, and changes of the bank structure. My idea in the future was to have a fixed folder inside the extension called migration, and through a CLI command of the copona, the developer creates a new migration file within its extension, and following a documentation, it can make the necessary modifications, including The module's install and unisntall methods would trigger these migrations when installed, and when uninstalling the module, would automatically give the migration rollback.

**Comment by arnisjuraga** [comment]
Yes, @lucasjkr has already converted table structure to InnoDB, 
I think - no need to create a migration for that anymore, as Copona installation anyway has to be done from fresh if needed.

All the other questions on this can be discussed on other threads.
