### ISSUE TITLE
Pagination missing Next, Last symbol

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#88]
In pagination, there is a problem with next, last, prev, first symbols.

I know, we have added a parameter to Pagination class, that we can hide prev,next and also last,first buttons,
and buttons itself can be added in translation file, 
but it seems, there is something wrong.
a) how we configure symbols?
b) the default and Simplica theme must have all of them - next, prev, last, first

@janistravins , please fix it:

![image](https://cloud.githubusercontent.com/assets/2185289/23238865/c5544cdc-f96c-11e6-9f90-41e79a362f11.png)

**Comment by janistravins** [comment]
Fixed in default and simplica themes. 
To change arrow settings, check this wiki: 
https://github.com/copona/copona/wiki/Theme-directory-functions
