### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by lucasjkr** [copona/copona#91]
I’m working on one of my pet peeves of OC - removing/replacing/augmenting insecure salting and password hashing algorithms, and wanted to share progress, etc.

• I’ve created a phinx migration to expand the password columns to 255 characters
• New account creation (admin, users, affiliates, customers) all have their passwords hashed with the password_hash function
• Logins now check against the password_verify function
---

I took note of Arnis' pointer, that if a password is forgotten, it's currently easier just to insert a new hashed password through PhpMyAdmin. There's also a potential need to migrate users old passwords to the new system (if people migrated/upgraded a store).

So, if the admin inserts a new password in PHPMYadmin the old fashioned way and then logs in (and also, if a user with an old style password logs in), it verifies that password, and then updates it to use the more secure hashing.

I have all of that working right now. We can determine which password type it is based on whether there is anything in the salt column (updating the password hash also sets the salt to empty), or the length of the string (if its an old style password reset that just puts a string in the password field) - this is based on the length of the hash.

But my next issue is that OC apparently allows duplicate user names, so long as they have unique emails. I don't think this should be allowable behavior and would like to stop that as well, but first I wanted to check if you guys think that there would ever be a valid use case for having a different accounts (user, affiliate or customer) with identical usernames?  Or should that be considered a flaw of OC? The issue is, with regards to migrating old data into it, an import could potentially break if we indexed the column, and username look ups will be inconsistent where duplicate usernames are present

Thoughts?.

**Comment by ADDCreative** [comment]
I don't think there is any valid case that there should be any duplicate usernames. The admin user controller checks this before adding. https://github.com/copona/copona/blob/master/admin/controller/user/user.php#L465-L475
So the only way would be if someone added directly to the database. Or is there another way to add a user?

Customer and affiliates don't have usernames, just email addresses.

**Comment by lucasjkr** [comment]
I'm just going by the indexes and queries, where the only required fields by the database are user_id and date_added. You can, in fact, create duplicate user names in the database (if you're doing it by hand), and both would work because the login query looks specifically for a record that has a matching username and a password that matches the hashed salt plus user supplied password.

I suppose OC's reasoning is if someone is adding records to the database by hand the system has already been broken into, but I'd rather use the database to validate where possible, just to preclude stuff like that from happening inadvertently...

Customers and affiliates could still be created with duplicate email addresses, again, if the validation got broken. More importantly, since customers log in with their email address and not their user_id, the email address should be indexed anyways.

Which is another thing I'm working on, analyzing queries and creating indexes where needed. Mostly multicolumn indexes to help specific queries, but other obvious things that were overlooked (like email address) are getting added as well. That'll be a separate pull request though, one thing at a time...

**Comment by arnisjuraga** [comment]
* no, there is no need for users with an identical username. Validation can be done in the database, I think - there is no harm. As @ADDCreative noted - user creation still should be validated in PHP, because it's easier. But for security - we can add an additional unique index in db, I think.

**Comment by lucasjkr** [comment]
Yes, I agree with you both. I added keys to the email fields (and username for users) currently. Will go ahead and make those unique at a later date, but will continue to rely on PHP doing the validation.
