### ISSUE TITLE
Is it so? php-xml is required? Then it should be checked during install in Copona too

### ISSUE THREAD

**Issue by arnisjuraga** [copona/copona#97]
Or it's only php 7 issue?

https://github.com/opencart/opencart/issues/5226

**Comment by miracleman** [comment]
don't know if this is a module since php7 but it seems more people have this issue so it would be nice if the installer could check this prerequisite.

https://www.google.de/search?client=ubuntu&channel=fs&q=Fatal+error%3A+Class+%27DOMDocument%27+not+found+opencart&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=BUyzWMSSEO6A8QeItoKwDg

**Comment by lucasjkr** [comment]
Just checking before I do this - at install Step 2, I should just check whether certain extensions are loaded?

    $modules = get_loaded_extensions();

And then search that array for `dom`, `libxml` and `xmlreader`? As it looks like we need to check for both from my reading of it?

I can do, but I can only test on PHP7 for the moment.

**Comment by arnisjuraga** [comment]
For this one, I think, it's enough to check, if required class exists:

https://www.drupal.org/files/issues/php_dom_requirement_00.patch

```php
if (class_exists('DOMDocument')) {
...
```

**Comment by arnisjuraga** [comment]
@miracleman Please, can you try this one and test? Don't be surprised! It's Copona!
#103

**Comment by miracleman** [comment]
@arnisjuraga I cab only test on php7 too. Just curious What is the project copona all about? Where are the differences? to opencart. (I'm new to opencart and try to build a multi-vendor marketplace with webkul's plugin)

**Comment by arnisjuraga** [comment]
1) we do not support modules ... :) and this is cool thing, - as we are completely free to change everything!

Check our commit or issues history, or here:

https://github.com/copona/copona/wiki

Some changes, here:

https://github.com/copona/copona/wiki/Improvements-over-Opencart

**Comment by lucasjkr** [comment]
Once this is checked by someone else, lets close this issue. :)

**Comment by arnisjuraga** [comment]
https://github.com/opencart/opencart/issues/5112
